### ISSUE TITLE
[Tangram R&D] Support specific tangram features in CartoCSS

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-cartocss#40]
We are supporting those properties that we had in mapnik, but we are leaving those news that vector brings to us.

To make them available I'll start to add support for some of them, like extrude.

As specific property key, I'd choose `tg` so, extrude will be `tg-extrude`

This came up after a talk with @AbelVM, what do you think?

**Comment by rochoa** [comment]
This is too generic/broad. We will create more specific issues when we decide what really adds value.
